/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables.records;


import de.quinscape.automatontemplate.domain.tables.AppConfig;
import de.quinscape.domainql.jsonb.JSONB;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "app_config", schema = "public", indexes = {
    @Index(name = "pk_app_config", unique = true, columnList = "name ASC")
})
public class AppConfigRecord extends UpdatableRecordImpl<AppConfigRecord> implements Record2<String, JSONB> {

    private static final long serialVersionUID = 246969747;

    /**
     * Setter for <code>public.app_config.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_config.name</code>.
     */
    @Id
    @Column(name = "name", unique = true, nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_config.scope</code>.
     */
    public void setScope(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_config.scope</code>.
     */
    @Column(name = "scope", nullable = false)
    @NotNull
    public JSONB getScope() {
        return (JSONB) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, JSONB> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, JSONB> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AppConfig.APP_CONFIG.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JSONB> field2() {
        return AppConfig.APP_CONFIG.SCOPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JSONB component2() {
        return getScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JSONB value2() {
        return getScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppConfigRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppConfigRecord value2(JSONB value) {
        setScope(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppConfigRecord values(String value1, JSONB value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppConfigRecord
     */
    public AppConfigRecord() {
        super(AppConfig.APP_CONFIG);
    }

    /**
     * Create a detached, initialised AppConfigRecord
     */
    public AppConfigRecord(String name, JSONB scope) {
        super(AppConfig.APP_CONFIG);

        set(0, name);
        set(1, scope);
    }
}
