/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables.records;


import de.quinscape.automatontemplate.domain.tables.AppTranslation;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "app_translation", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"locale", "tag", "process_name"})
}, indexes = {
    @Index(name = "pk_app_translation", unique = true, columnList = "id ASC"),
    @Index(name = "uc_app_translation", unique = true, columnList = "locale ASC, tag ASC, process_name ASC")
})
public class AppTranslationRecord extends UpdatableRecordImpl<AppTranslationRecord> implements Record7<String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -951569258;

    /**
     * Setter for <code>public.app_translation.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_translation.id</code>.
     */
    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_translation.locale</code>.
     */
    public void setLocale(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_translation.locale</code>.
     */
    @Column(name = "locale", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getLocale() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_translation.tag</code>.
     */
    public void setTag(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_translation.tag</code>.
     */
    @Column(name = "tag", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getTag() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_translation.process_name</code>.
     */
    public void setProcessName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_translation.process_name</code>.
     */
    @Column(name = "process_name", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getProcessName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.app_translation.translation</code>.
     */
    public void setTranslation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.app_translation.translation</code>.
     */
    @Column(name = "translation", nullable = false)
    @NotNull
    public String getTranslation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.app_translation.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.app_translation.created</code>.
     */
    @Column(name = "created", nullable = false)
    @NotNull
    public Timestamp getCreated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.app_translation.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.app_translation.modified</code>.
     */
    @Column(name = "modified", nullable = false)
    @NotNull
    public Timestamp getModified() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AppTranslation.APP_TRANSLATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AppTranslation.APP_TRANSLATION.LOCALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AppTranslation.APP_TRANSLATION.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AppTranslation.APP_TRANSLATION.PROCESS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AppTranslation.APP_TRANSLATION.TRANSLATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return AppTranslation.APP_TRANSLATION.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return AppTranslation.APP_TRANSLATION.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLocale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProcessName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTranslation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLocale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProcessName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTranslation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslationRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslationRecord value2(String value) {
        setLocale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslationRecord value3(String value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslationRecord value4(String value) {
        setProcessName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslationRecord value5(String value) {
        setTranslation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslationRecord value6(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslationRecord value7(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslationRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppTranslationRecord
     */
    public AppTranslationRecord() {
        super(AppTranslation.APP_TRANSLATION);
    }

    /**
     * Create a detached, initialised AppTranslationRecord
     */
    public AppTranslationRecord(String id, String locale, String tag, String processName, String translation, Timestamp created, Timestamp modified) {
        super(AppTranslation.APP_TRANSLATION);

        set(0, id);
        set(1, locale);
        set(2, tag);
        set(3, processName);
        set(4, translation);
        set(5, created);
        set(6, modified);
    }
}
