/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables.records;


import de.quinscape.automatontemplate.domain.tables.AppVersion;

import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "app_version", schema = "public", indexes = {
    @Index(name = "pk_app_version", unique = true, columnList = "id ASC")
})
public class AppVersionRecord extends UpdatableRecordImpl<AppVersionRecord> implements Record7<String, BigInteger, String, Timestamp, String, String, String> {

    private static final long serialVersionUID = 1227231663;

    /**
     * Setter for <code>public.app_version.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_version.id</code>.
     */
    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_version.field_mask</code>.
     */
    public void setFieldMask(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_version.field_mask</code>.
     */
    @Column(name = "field_mask", nullable = false, precision = 39)
    @NotNull
    public BigInteger getFieldMask() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>public.app_version.owner_id</code>.
     */
    public void setOwnerId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_version.owner_id</code>.
     */
    @Column(name = "owner_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getOwnerId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_version.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_version.created</code>.
     */
    @Column(name = "created", nullable = false)
    @NotNull
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.app_version.entity_type</code>.
     */
    public void setEntityType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.app_version.entity_type</code>.
     */
    @Column(name = "entity_type", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getEntityType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.app_version.entity_id</code>.
     */
    public void setEntityId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.app_version.entity_id</code>.
     */
    @Column(name = "entity_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getEntityId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.app_version.prev</code>.
     */
    public void setPrev(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.app_version.prev</code>.
     */
    @Column(name = "prev", length = 36)
    @Size(max = 36)
    public String getPrev() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, BigInteger, String, Timestamp, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, BigInteger, String, Timestamp, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AppVersion.APP_VERSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field2() {
        return AppVersion.APP_VERSION.FIELD_MASK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AppVersion.APP_VERSION.OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return AppVersion.APP_VERSION.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AppVersion.APP_VERSION.ENTITY_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AppVersion.APP_VERSION.ENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AppVersion.APP_VERSION.PREV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component2() {
        return getFieldMask();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getEntityType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPrev();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value2() {
        return getFieldMask();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEntityType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPrev();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersionRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersionRecord value2(BigInteger value) {
        setFieldMask(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersionRecord value3(String value) {
        setOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersionRecord value4(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersionRecord value5(String value) {
        setEntityType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersionRecord value6(String value) {
        setEntityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersionRecord value7(String value) {
        setPrev(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersionRecord values(String value1, BigInteger value2, String value3, Timestamp value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppVersionRecord
     */
    public AppVersionRecord() {
        super(AppVersion.APP_VERSION);
    }

    /**
     * Create a detached, initialised AppVersionRecord
     */
    public AppVersionRecord(String id, BigInteger fieldMask, String ownerId, Timestamp created, String entityType, String entityId, String prev) {
        super(AppVersion.APP_VERSION);

        set(0, id);
        set(1, fieldMask);
        set(2, ownerId);
        set(3, created);
        set(4, entityType);
        set(5, entityId);
        set(6, prev);
    }
}
