/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables.records;


import de.quinscape.automatontemplate.domain.tables.DomainFieldMeta;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "domain_field_meta", schema = "public", indexes = {
    @Index(name = "pk_domain_field_meta", unique = true, columnList = "id ASC")
})
public class DomainFieldMetaRecord extends UpdatableRecordImpl<DomainFieldMetaRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = -1121691791;

    /**
     * Setter for <code>public.domain_field_meta.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.domain_field_meta.id</code>.
     */
    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.domain_field_meta.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.domain_field_meta.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.domain_field_meta.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.domain_field_meta.value</code>.
     */
    @Column(name = "value", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.domain_field_meta.domain_field_id</code>.
     */
    public void setDomainFieldId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.domain_field_meta.domain_field_id</code>.
     */
    @Column(name = "domain_field_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getDomainFieldId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DomainFieldMeta.DOMAIN_FIELD_META.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DomainFieldMeta.DOMAIN_FIELD_META.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DomainFieldMeta.DOMAIN_FIELD_META.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DomainFieldMeta.DOMAIN_FIELD_META.DOMAIN_FIELD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDomainFieldId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDomainFieldId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DomainFieldMetaRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DomainFieldMetaRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DomainFieldMetaRecord value3(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DomainFieldMetaRecord value4(String value) {
        setDomainFieldId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DomainFieldMetaRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DomainFieldMetaRecord
     */
    public DomainFieldMetaRecord() {
        super(DomainFieldMeta.DOMAIN_FIELD_META);
    }

    /**
     * Create a detached, initialised DomainFieldMetaRecord
     */
    public DomainFieldMetaRecord(String id, String name, String value, String domainFieldId) {
        super(DomainFieldMeta.DOMAIN_FIELD_META);

        set(0, id);
        set(1, name);
        set(2, value);
        set(3, domainFieldId);
    }
}
