/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables;


import de.quinscape.automatontemplate.domain.Indexes;
import de.quinscape.automatontemplate.domain.Keys;
import de.quinscape.automatontemplate.domain.Public;
import de.quinscape.automatontemplate.domain.tables.records.AppConfigRecord;
import de.quinscape.domainql.jsonb.JSONB;
import de.quinscape.domainql.jsonb.PGJSONBinding;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppConfig extends TableImpl<AppConfigRecord> {

    private static final long serialVersionUID = -1267067137;

    /**
     * The reference instance of <code>public.app_config</code>
     */
    public static final AppConfig APP_CONFIG = new AppConfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppConfigRecord> getRecordType() {
        return AppConfigRecord.class;
    }

    /**
     * The column <code>public.app_config.name</code>.
     */
    public final TableField<AppConfigRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_config.scope</code>.
     */
    public final TableField<AppConfigRecord, JSONB> SCOPE = createField("scope", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "", new PGJSONBinding());

    /**
     * Create a <code>public.app_config</code> table reference
     */
    public AppConfig() {
        this(DSL.name("app_config"), null);
    }

    /**
     * Create an aliased <code>public.app_config</code> table reference
     */
    public AppConfig(String alias) {
        this(DSL.name(alias), APP_CONFIG);
    }

    /**
     * Create an aliased <code>public.app_config</code> table reference
     */
    public AppConfig(Name alias) {
        this(alias, APP_CONFIG);
    }

    private AppConfig(Name alias, Table<AppConfigRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppConfig(Name alias, Table<AppConfigRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_APP_CONFIG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppConfigRecord> getPrimaryKey() {
        return Keys.PK_APP_CONFIG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppConfigRecord>> getKeys() {
        return Arrays.<UniqueKey<AppConfigRecord>>asList(Keys.PK_APP_CONFIG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppConfig as(String alias) {
        return new AppConfig(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppConfig as(Name alias) {
        return new AppConfig(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppConfig rename(String name) {
        return new AppConfig(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppConfig rename(Name name) {
        return new AppConfig(name, null);
    }
}
