/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables;


import de.quinscape.automatontemplate.domain.Indexes;
import de.quinscape.automatontemplate.domain.Keys;
import de.quinscape.automatontemplate.domain.Public;
import de.quinscape.automatontemplate.domain.tables.records.AppTranslationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppTranslation extends TableImpl<AppTranslationRecord> {

    private static final long serialVersionUID = 90275977;

    /**
     * The reference instance of <code>public.app_translation</code>
     */
    public static final AppTranslation APP_TRANSLATION = new AppTranslation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppTranslationRecord> getRecordType() {
        return AppTranslationRecord.class;
    }

    /**
     * The column <code>public.app_translation.id</code>.
     */
    public final TableField<AppTranslationRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_translation.locale</code>.
     */
    public final TableField<AppTranslationRecord, String> LOCALE = createField("locale", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_translation.tag</code>.
     */
    public final TableField<AppTranslationRecord, String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.app_translation.process_name</code>.
     */
    public final TableField<AppTranslationRecord, String> PROCESS_NAME = createField("process_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_translation.translation</code>.
     */
    public final TableField<AppTranslationRecord, String> TRANSLATION = createField("translation", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.app_translation.created</code>.
     */
    public final TableField<AppTranslationRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.app_translation.modified</code>.
     */
    public final TableField<AppTranslationRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.app_translation</code> table reference
     */
    public AppTranslation() {
        this(DSL.name("app_translation"), null);
    }

    /**
     * Create an aliased <code>public.app_translation</code> table reference
     */
    public AppTranslation(String alias) {
        this(DSL.name(alias), APP_TRANSLATION);
    }

    /**
     * Create an aliased <code>public.app_translation</code> table reference
     */
    public AppTranslation(Name alias) {
        this(alias, APP_TRANSLATION);
    }

    private AppTranslation(Name alias, Table<AppTranslationRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppTranslation(Name alias, Table<AppTranslationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_APP_TRANSLATION, Indexes.UC_APP_TRANSLATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppTranslationRecord> getPrimaryKey() {
        return Keys.PK_APP_TRANSLATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppTranslationRecord>> getKeys() {
        return Arrays.<UniqueKey<AppTranslationRecord>>asList(Keys.PK_APP_TRANSLATION, Keys.UC_APP_TRANSLATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslation as(String alias) {
        return new AppTranslation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTranslation as(Name alias) {
        return new AppTranslation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppTranslation rename(String name) {
        return new AppTranslation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppTranslation rename(Name name) {
        return new AppTranslation(name, null);
    }
}
