/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables;


import de.quinscape.automatontemplate.domain.Indexes;
import de.quinscape.automatontemplate.domain.Keys;
import de.quinscape.automatontemplate.domain.Public;
import de.quinscape.automatontemplate.domain.tables.records.AppUserConfigRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserConfig extends TableImpl<AppUserConfigRecord> {

    private static final long serialVersionUID = 1170857579;

    /**
     * The reference instance of <code>public.app_user_config</code>
     */
    public static final AppUserConfig APP_USER_CONFIG = new AppUserConfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppUserConfigRecord> getRecordType() {
        return AppUserConfigRecord.class;
    }

    /**
     * The column <code>public.app_user_config.login</code>.
     */
    public final TableField<AppUserConfigRecord, String> LOGIN = createField("login", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_user_config.user_id</code>.
     */
    public final TableField<AppUserConfigRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.app_user_config</code> table reference
     */
    public AppUserConfig() {
        this(DSL.name("app_user_config"), null);
    }

    /**
     * Create an aliased <code>public.app_user_config</code> table reference
     */
    public AppUserConfig(String alias) {
        this(DSL.name(alias), APP_USER_CONFIG);
    }

    /**
     * Create an aliased <code>public.app_user_config</code> table reference
     */
    public AppUserConfig(Name alias) {
        this(alias, APP_USER_CONFIG);
    }

    private AppUserConfig(Name alias, Table<AppUserConfigRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppUserConfig(Name alias, Table<AppUserConfigRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_APP_USER_CONFIG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppUserConfigRecord> getPrimaryKey() {
        return Keys.PK_APP_USER_CONFIG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppUserConfigRecord>> getKeys() {
        return Arrays.<UniqueKey<AppUserConfigRecord>>asList(Keys.PK_APP_USER_CONFIG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AppUserConfigRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AppUserConfigRecord, ?>>asList(Keys.APP_USER_CONFIG__FK_APP_USER_CONFIG_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserConfig as(String alias) {
        return new AppUserConfig(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppUserConfig as(Name alias) {
        return new AppUserConfig(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserConfig rename(String name) {
        return new AppUserConfig(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserConfig rename(Name name) {
        return new AppUserConfig(name, null);
    }
}
