/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables;


import de.quinscape.automatontemplate.domain.Indexes;
import de.quinscape.automatontemplate.domain.Keys;
import de.quinscape.automatontemplate.domain.Public;
import de.quinscape.automatontemplate.domain.tables.records.AppVersionRecord;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppVersion extends TableImpl<AppVersionRecord> {

    private static final long serialVersionUID = 160266213;

    /**
     * The reference instance of <code>public.app_version</code>
     */
    public static final AppVersion APP_VERSION = new AppVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppVersionRecord> getRecordType() {
        return AppVersionRecord.class;
    }

    /**
     * The column <code>public.app_version.id</code>.
     */
    public final TableField<AppVersionRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_version.field_mask</code>.
     */
    public final TableField<AppVersionRecord, BigInteger> FIELD_MASK = createField("field_mask", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(39).nullable(false), this, "");

    /**
     * The column <code>public.app_version.owner_id</code>.
     */
    public final TableField<AppVersionRecord, String> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_version.created</code>.
     */
    public final TableField<AppVersionRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.app_version.entity_type</code>.
     */
    public final TableField<AppVersionRecord, String> ENTITY_TYPE = createField("entity_type", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.app_version.entity_id</code>.
     */
    public final TableField<AppVersionRecord, String> ENTITY_ID = createField("entity_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_version.prev</code>.
     */
    public final TableField<AppVersionRecord, String> PREV = createField("prev", org.jooq.impl.SQLDataType.VARCHAR(36), this, "");

    /**
     * Create a <code>public.app_version</code> table reference
     */
    public AppVersion() {
        this(DSL.name("app_version"), null);
    }

    /**
     * Create an aliased <code>public.app_version</code> table reference
     */
    public AppVersion(String alias) {
        this(DSL.name(alias), APP_VERSION);
    }

    /**
     * Create an aliased <code>public.app_version</code> table reference
     */
    public AppVersion(Name alias) {
        this(alias, APP_VERSION);
    }

    private AppVersion(Name alias, Table<AppVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppVersion(Name alias, Table<AppVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_APP_VERSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppVersionRecord> getPrimaryKey() {
        return Keys.PK_APP_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppVersionRecord>> getKeys() {
        return Arrays.<UniqueKey<AppVersionRecord>>asList(Keys.PK_APP_VERSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AppVersionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AppVersionRecord, ?>>asList(Keys.APP_VERSION__FK_APP_VERSION_OWNER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersion as(String alias) {
        return new AppVersion(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppVersion as(Name alias) {
        return new AppVersion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppVersion rename(String name) {
        return new AppVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppVersion rename(Name name) {
        return new AppVersion(name, null);
    }
}
