/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables;


import de.quinscape.automatontemplate.domain.Indexes;
import de.quinscape.automatontemplate.domain.Keys;
import de.quinscape.automatontemplate.domain.Public;
import de.quinscape.automatontemplate.domain.tables.records.DomainTypeMetaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DomainTypeMeta extends TableImpl<DomainTypeMetaRecord> {

    private static final long serialVersionUID = -678378599;

    /**
     * The reference instance of <code>public.domain_type_meta</code>
     */
    public static final DomainTypeMeta DOMAIN_TYPE_META = new DomainTypeMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DomainTypeMetaRecord> getRecordType() {
        return DomainTypeMetaRecord.class;
    }

    /**
     * The column <code>public.domain_type_meta.id</code>.
     */
    public final TableField<DomainTypeMetaRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.domain_type_meta.name</code>.
     */
    public final TableField<DomainTypeMetaRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.domain_type_meta.value</code>.
     */
    public final TableField<DomainTypeMetaRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.domain_type_meta.domain_type_id</code>.
     */
    public final TableField<DomainTypeMetaRecord, String> DOMAIN_TYPE_ID = createField("domain_type_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.domain_type_meta</code> table reference
     */
    public DomainTypeMeta() {
        this(DSL.name("domain_type_meta"), null);
    }

    /**
     * Create an aliased <code>public.domain_type_meta</code> table reference
     */
    public DomainTypeMeta(String alias) {
        this(DSL.name(alias), DOMAIN_TYPE_META);
    }

    /**
     * Create an aliased <code>public.domain_type_meta</code> table reference
     */
    public DomainTypeMeta(Name alias) {
        this(alias, DOMAIN_TYPE_META);
    }

    private DomainTypeMeta(Name alias, Table<DomainTypeMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private DomainTypeMeta(Name alias, Table<DomainTypeMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_DOMAIN_TYPE_META);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DomainTypeMetaRecord> getPrimaryKey() {
        return Keys.PK_DOMAIN_TYPE_META;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DomainTypeMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<DomainTypeMetaRecord>>asList(Keys.PK_DOMAIN_TYPE_META);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DomainTypeMetaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DomainTypeMetaRecord, ?>>asList(Keys.DOMAIN_TYPE_META__FK_DOMAIN_TYPE_META_TYPE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DomainTypeMeta as(String alias) {
        return new DomainTypeMeta(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DomainTypeMeta as(Name alias) {
        return new DomainTypeMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DomainTypeMeta rename(String name) {
        return new DomainTypeMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DomainTypeMeta rename(Name name) {
        return new DomainTypeMeta(name, null);
    }
}
