/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables;


import de.quinscape.automatontemplate.domain.Indexes;
import de.quinscape.automatontemplate.domain.Keys;
import de.quinscape.automatontemplate.domain.Public;
import de.quinscape.automatontemplate.domain.tables.records.DomainFieldMetaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DomainFieldMeta extends TableImpl<DomainFieldMetaRecord> {

    private static final long serialVersionUID = -828906589;

    /**
     * The reference instance of <code>public.domain_field_meta</code>
     */
    public static final DomainFieldMeta DOMAIN_FIELD_META = new DomainFieldMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DomainFieldMetaRecord> getRecordType() {
        return DomainFieldMetaRecord.class;
    }

    /**
     * The column <code>public.domain_field_meta.id</code>.
     */
    public final TableField<DomainFieldMetaRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.domain_field_meta.name</code>.
     */
    public final TableField<DomainFieldMetaRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.domain_field_meta.value</code>.
     */
    public final TableField<DomainFieldMetaRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.domain_field_meta.domain_field_id</code>.
     */
    public final TableField<DomainFieldMetaRecord, String> DOMAIN_FIELD_ID = createField("domain_field_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.domain_field_meta</code> table reference
     */
    public DomainFieldMeta() {
        this(DSL.name("domain_field_meta"), null);
    }

    /**
     * Create an aliased <code>public.domain_field_meta</code> table reference
     */
    public DomainFieldMeta(String alias) {
        this(DSL.name(alias), DOMAIN_FIELD_META);
    }

    /**
     * Create an aliased <code>public.domain_field_meta</code> table reference
     */
    public DomainFieldMeta(Name alias) {
        this(alias, DOMAIN_FIELD_META);
    }

    private DomainFieldMeta(Name alias, Table<DomainFieldMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private DomainFieldMeta(Name alias, Table<DomainFieldMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_DOMAIN_FIELD_META);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DomainFieldMetaRecord> getPrimaryKey() {
        return Keys.PK_DOMAIN_FIELD_META;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DomainFieldMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<DomainFieldMetaRecord>>asList(Keys.PK_DOMAIN_FIELD_META);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DomainFieldMetaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DomainFieldMetaRecord, ?>>asList(Keys.DOMAIN_FIELD_META__FK_DOMAIN_FIELD_META_FIELD_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DomainFieldMeta as(String alias) {
        return new DomainFieldMeta(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DomainFieldMeta as(Name alias) {
        return new DomainFieldMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DomainFieldMeta rename(String name) {
        return new DomainFieldMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DomainFieldMeta rename(Name name) {
        return new DomainFieldMeta(name, null);
    }
}
