/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;
import de.quinscape.domainql.jsonb.JSONB;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "app_config", schema = "public", indexes = {
    @Index(name = "pk_app_config", unique = true, columnList = "name ASC")
})
public class AppConfig extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = -380139810;

    private String name;
    private JSONB  scope;

    public AppConfig() {}

    public AppConfig(AppConfig value) {
        this.name = value.name;
        this.scope = value.scope;
    }

    public AppConfig(
        String name,
        JSONB  scope
    ) {
        this.name = name;
        this.scope = scope;
    }

    @Id
    @Column(name = "name", unique = true, nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "scope", nullable = false)
    @NotNull
    public JSONB getScope() {
        return this.scope;
    }

    public void setScope(JSONB scope) {
        this.scope = scope;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppConfig (");

        sb.append(name);
        sb.append(", ").append(scope);

        sb.append(")");
        return sb.toString();
    }
}
