/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "app_user_config", schema = "public", indexes = {
    @Index(name = "pk_app_user_config", unique = true, columnList = "login ASC")
})
public class AppUserConfig extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 2067183174;

    private String login;
    private String userId;

    public AppUserConfig() {}

    public AppUserConfig(AppUserConfig value) {
        this.login = value.login;
        this.userId = value.userId;
    }

    public AppUserConfig(
        String login,
        String userId
    ) {
        this.login = login;
        this.userId = userId;
    }

    @Id
    @Column(name = "login", unique = true, nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "user_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppUserConfig (");

        sb.append(login);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
