/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "domain_field_meta", schema = "public", indexes = {
    @Index(name = "pk_domain_field_meta", unique = true, columnList = "id ASC")
})
public class DomainFieldMeta extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = -1821541149;

    private String id;
    private String name;
    private String value;
    private String domainFieldId;

    public DomainFieldMeta() {}

    public DomainFieldMeta(DomainFieldMeta value) {
        this.id = value.id;
        this.name = value.name;
        this.value = value.value;
        this.domainFieldId = value.domainFieldId;
    }

    public DomainFieldMeta(
        String id,
        String name,
        String value,
        String domainFieldId
    ) {
        this.id = id;
        this.name = name;
        this.value = value;
        this.domainFieldId = domainFieldId;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "value", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "domain_field_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getDomainFieldId() {
        return this.domainFieldId;
    }

    public void setDomainFieldId(String domainFieldId) {
        this.domainFieldId = domainFieldId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DomainFieldMeta (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(value);
        sb.append(", ").append(domainFieldId);

        sb.append(")");
        return sb.toString();
    }
}
