/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "domain_field", schema = "public", indexes = {
    @Index(name = "pk_domain_field", unique = true, columnList = "id ASC")
})
public class DomainField extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 2102249341;

    private String  id;
    private String  name;
    private String  type;
    private String  description;
    private String  domainTypeId;
    private Boolean important;

    public DomainField() {}

    public DomainField(DomainField value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
        this.description = value.description;
        this.domainTypeId = value.domainTypeId;
        this.important = value.important;
    }

    public DomainField(
        String  id,
        String  name,
        String  type,
        String  description,
        String  domainTypeId,
        Boolean important
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.description = description;
        this.domainTypeId = domainTypeId;
        this.important = important;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "name", length = 100)
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "type", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "domain_type_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getDomainTypeId() {
        return this.domainTypeId;
    }

    public void setDomainTypeId(String domainTypeId) {
        this.domainTypeId = domainTypeId;
    }

    @Column(name = "important", nullable = false)
    @NotNull
    public Boolean getImportant() {
        return this.important;
    }

    public void setImportant(Boolean important) {
        this.important = important;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DomainField (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(description);
        sb.append(", ").append(domainTypeId);
        sb.append(", ").append(important);

        sb.append(")");
        return sb.toString();
    }
}
