/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "domain_type", schema = "public", indexes = {
    @Index(name = "pk_domain_type", unique = true, columnList = "id ASC")
})
public class DomainType extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = -1156524961;

    private String id;
    private String name;
    private String description;
    private String appId;

    public DomainType() {}

    public DomainType(DomainType value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.appId = value.appId;
    }

    public DomainType(
        String id,
        String name,
        String description,
        String appId
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.appId = appId;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "app_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DomainType (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(appId);

        sb.append(")");
        return sb.toString();
    }
}
