/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain;


import de.quinscape.automatontemplate.domain.tables.AppConfig;
import de.quinscape.automatontemplate.domain.tables.AppLogin;
import de.quinscape.automatontemplate.domain.tables.AppTranslation;
import de.quinscape.automatontemplate.domain.tables.AppUser;
import de.quinscape.automatontemplate.domain.tables.AppUserConfig;
import de.quinscape.automatontemplate.domain.tables.AppVersion;
import de.quinscape.automatontemplate.domain.tables.Foo;
import de.quinscape.automatontemplate.domain.tables.FooType;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -992148316;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.app_config</code>.
     */
    public final AppConfig APP_CONFIG = de.quinscape.automatontemplate.domain.tables.AppConfig.APP_CONFIG;

    /**
     * The table <code>public.app_login</code>.
     */
    public final AppLogin APP_LOGIN = de.quinscape.automatontemplate.domain.tables.AppLogin.APP_LOGIN;

    /**
     * The table <code>public.app_translation</code>.
     */
    public final AppTranslation APP_TRANSLATION = de.quinscape.automatontemplate.domain.tables.AppTranslation.APP_TRANSLATION;

    /**
     * The table <code>public.app_user</code>.
     */
    public final AppUser APP_USER = de.quinscape.automatontemplate.domain.tables.AppUser.APP_USER;

    /**
     * The table <code>public.app_user_config</code>.
     */
    public final AppUserConfig APP_USER_CONFIG = de.quinscape.automatontemplate.domain.tables.AppUserConfig.APP_USER_CONFIG;

    /**
     * The table <code>public.app_version</code>.
     */
    public final AppVersion APP_VERSION = de.quinscape.automatontemplate.domain.tables.AppVersion.APP_VERSION;

    /**
     * The table <code>public.foo</code>.
     */
    public final Foo FOO = de.quinscape.automatontemplate.domain.tables.Foo.FOO;

    /**
     * The table <code>public.foo_type</code>.
     */
    public final FooType FOO_TYPE = de.quinscape.automatontemplate.domain.tables.FooType.FOO_TYPE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AppConfig.APP_CONFIG,
            AppLogin.APP_LOGIN,
            AppTranslation.APP_TRANSLATION,
            AppUser.APP_USER,
            AppUserConfig.APP_USER_CONFIG,
            AppVersion.APP_VERSION,
            Foo.FOO,
            FooType.FOO_TYPE);
    }
}
