/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontemplate.domain;


import de.quinscape.automatontemplate.domain.tables.App;
import de.quinscape.automatontemplate.domain.tables.AppAttachment;
import de.quinscape.automatontemplate.domain.tables.AppAttachmentData;
import de.quinscape.automatontemplate.domain.tables.AppConfig;
import de.quinscape.automatontemplate.domain.tables.AppLogin;
import de.quinscape.automatontemplate.domain.tables.AppTranslation;
import de.quinscape.automatontemplate.domain.tables.AppUser;
import de.quinscape.automatontemplate.domain.tables.AppUserConfig;
import de.quinscape.automatontemplate.domain.tables.AppVersion;
import de.quinscape.automatontemplate.domain.tables.DomainField;
import de.quinscape.automatontemplate.domain.tables.DomainFieldMeta;
import de.quinscape.automatontemplate.domain.tables.DomainType;
import de.quinscape.automatontemplate.domain.tables.DomainTypeMeta;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.app</code>.
     */
    public static final App APP = de.quinscape.automatontemplate.domain.tables.App.APP;

    /**
     * The table <code>public.app_attachment</code>.
     */
    public static final AppAttachment APP_ATTACHMENT = de.quinscape.automatontemplate.domain.tables.AppAttachment.APP_ATTACHMENT;

    /**
     * The table <code>public.app_attachment_data</code>.
     */
    public static final AppAttachmentData APP_ATTACHMENT_DATA = de.quinscape.automatontemplate.domain.tables.AppAttachmentData.APP_ATTACHMENT_DATA;

    /**
     * The table <code>public.app_config</code>.
     */
    public static final AppConfig APP_CONFIG = de.quinscape.automatontemplate.domain.tables.AppConfig.APP_CONFIG;

    /**
     * The table <code>public.app_login</code>.
     */
    public static final AppLogin APP_LOGIN = de.quinscape.automatontemplate.domain.tables.AppLogin.APP_LOGIN;

    /**
     * The table <code>public.app_translation</code>.
     */
    public static final AppTranslation APP_TRANSLATION = de.quinscape.automatontemplate.domain.tables.AppTranslation.APP_TRANSLATION;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = de.quinscape.automatontemplate.domain.tables.AppUser.APP_USER;

    /**
     * The table <code>public.app_user_config</code>.
     */
    public static final AppUserConfig APP_USER_CONFIG = de.quinscape.automatontemplate.domain.tables.AppUserConfig.APP_USER_CONFIG;

    /**
     * The table <code>public.app_version</code>.
     */
    public static final AppVersion APP_VERSION = de.quinscape.automatontemplate.domain.tables.AppVersion.APP_VERSION;

    /**
     * The table <code>public.domain_field</code>.
     */
    public static final DomainField DOMAIN_FIELD = de.quinscape.automatontemplate.domain.tables.DomainField.DOMAIN_FIELD;

    /**
     * The table <code>public.domain_field_meta</code>.
     */
    public static final DomainFieldMeta DOMAIN_FIELD_META = de.quinscape.automatontemplate.domain.tables.DomainFieldMeta.DOMAIN_FIELD_META;

    /**
     * The table <code>public.domain_type</code>.
     */
    public static final DomainType DOMAIN_TYPE = de.quinscape.automatontemplate.domain.tables.DomainType.DOMAIN_TYPE;

    /**
     * The table <code>public.domain_type_meta</code>.
     */
    public static final DomainTypeMeta DOMAIN_TYPE_META = de.quinscape.automatontemplate.domain.tables.DomainTypeMeta.DOMAIN_TYPE_META;
}
